spring:
  application:
    name: notify

  profiles:
    active: dev

# JPA 공통 옵션
spring.jpa:
  open-in-view: false
  hibernate:
    ddl-auto: update
  properties:
    hibernate.format_sql: true

logging:
  level:
    notify: DEBUG

cors:
  allowed-origins:
    - http://localhost:3000
    - https://your-frontend.example.com
  allowed-methods:
    - GET
    - POST
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
