
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/notify
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    com.example.notify: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notify?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


# Kafka도 비활성화
notify:
  kafka:
    enabled: false


auth:
  jwt:
    enabled: false



