spring:
  application:
    name: notify-service

  kafka:
    # ─────────────────────────────────────────────
    # Kafka 기본 설정 (OCI Kafka 호환 클러스터)
    # ─────────────────────────────────────────────
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_GROUP_ID:notify-group}
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      retries: 10
    listener:
      ack-mode: manual_immediate
    properties:
      # SASL/SCRAM 보안 설정
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";
      # 연결 안정성
      request.timeout.ms: 30000
      connections.max.idle.ms: 540000

# ─────────────────────────────────────────────
# 애플리케이션 전용 Kafka 토픽 구성
# (Debezium 이벤트 + 실시간 랭킹용)
# ─────────────────────────────────────────────
app:
  kafka:
    topic:
      userstock: finance.finance.userstock
      execution: finance.finance.execution
      dividend: finance.finance.dividendinfo
      ranking-output: notify.ranking.top10

    # 컨슈머 병렬성 (Listener Container 동시성)
    consumer:
      concurrency: 2
