spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notify
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.example.notify: DEBUG







