spring:
  datasource:
    url: jdbc:mysql://prod-mysql:3306/notify
    username: notify_user
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

logging:
  level:
    root: INFO
    nortify.notify: INFO
